development:
  adapter: async

test:
  adapter: test

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "") %>
  channel_prefix: kamal_workshops_app_staging

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "") %>
  channel_prefix: kamal_workshops_app_production
