# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_space_development

test:
  <<: *default
  database: blog_space_test

staging:
  <<: *default
  database: blog_space_staging
  url: <%= ENV["POSTGRES_URL"] %>

production:
  <<: *default
  database: blog_space_production
  url: <%= ENV["POSTGRES_URL"] %>
